# Generated by Django 5.2.5 on 2025-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="strip_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
