# Generated by Django 5.2.5 on 2025-09-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_course_strip_product_id_course_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name="Цена"),
        ),
    ]
