# Generated by Django 5.2.5 on 2025-09-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="strip_product_id",
            new_name="stripe_product_id",
        ),
    ]
