# Generated by Django 5.2.5 on 2025-09-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0007_rename_strip_product_id_course_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(max_length=500, verbose_name="ID сессии Stripe"),
        ),
    ]
