# Generated by Django 5.2.5 on 2025-09-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0008_alter_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(max_length=500, verbose_name="Ссылка на оплату"),
        ),
    ]
