name: CI/CD
on:
  push:
    branches: [ "feature/homework" ]
  pull_request:
    branches: [ "feature/homework" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: drf
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Akoros781
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      - name: Install redis-tools for redis-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools

      - name: Run migrations
        env:
          DB_NAME: drf
          DB_USER: postgres
          DB_PASSWORD: Akoros781
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_DB: 0
          DEBUG: True
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        env:
          DB_NAME: drf
          DB_USER: postgres
          DB_PASSWORD: Akoros781
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_DB: 0
          DEBUG: True
        run: |
          poetry run python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/feature/homework'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          environment_vars:
            DEPLOY_DIR_ON_SERVER={{ secrets.DEPLOY_DIR }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            
            # --- СОЗДАНИЕ .env ФАЙЛА НА СЕРВЕРЕ ---
            echo "--- Creating .env file on server ---"
            cat << 'EOF' > .env
            DB_NAME=${{ env.DB_NAME }}
            DB_USER=${{ env.DB_USER }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_HOST=db
            DB_PORT=5432
            SECRET_KEY=${{ env.SECRET_KEY }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
            CELERY_BROKER_URL=redis://redis:6379/0
            CELERY_RESULT_BACKEND=redis://redis:6379/0
            REDIS_HOST=redis
            REDIS_PORT=6379
            REDIS_DB=0
            DEBUG=False
            EOF
          # --- КОНЕЦ СОЗДАНИЯ .env ФАЙЛА ---

          script: |
            docker compose down
            
            echo "Rebuilding and starting containers"
            docker compose up -d --build
            
            echo "Running migrations and collecting static"
            docker compose exec web python manage.py migrate
            docker compose exec web python manage.py collectstatic --noinput
            
            echo "Deploy finished"